apiVersion: v1
kind: Service
metadata:
  name: psql-service
spec:
  type: NodePort
  selector:
    app: psql
  ports:
    - name: "postgres"
      protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30432
