apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: docker.io/library/web-dev
          imagePullPolicy: Never
          command: [ "bash", "-c", "dotnet build && dotnet ef database update && dotnet run" ]
          ports:
            - containerPort: 5000
              name: "http"
            - containerPort: 5001
              name: "https"
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: psql-secret
                  key: database
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: psql-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: psql-secret
                  key: password
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: psql-config
                  key: psql-url
            - name: CUSTOMCONNSTR_VehicleQuotesContext
              value: Host=$(DB_URL);Database=$(POSTGRES_DB);Username=$(POSTGRES_USER);Password=$(POSTGRES_PASSWORD)
